emotions = {
        "curiosity": [
            "eager to learn more",
            "full of questions",
            "exploring the unknown",
            "drawn to mystery",
            "wanting to understand",
            "fascinated by details",
            "open-minded and inquisitive",
            "searching for answers",
            "mentally engaged",
            "restless for discovery"
            ],
        "betrayal": [
            "stabbed in the back",
            "trust shattered",
            "feeling deeply wronged",
            "cut by disloyalty",
            "a friend turned foe",
            "lost all faith",
            "devastated by deceit",
            "wounded by lies",
            "left in disbelief",
            "heart broken by treachery"
            ],
        "gratitude": [
            "thankful from the heart",
            "feeling truly blessed",
            "grateful for kindness",
            "appreciating every moment",
            "recognizing the good",
            "a heart full of thanks",
            "honoring generosity",
            "touched by support",
            "deep appreciation",
            "smiling with gratitude"
            ],
        "embarrassment": [
            "blushing uncontrollably",
            "caught in an awkward moment",
            "wanting to disappear",
            "laughing nervously",
            "feeling exposed",
            "social discomfort",
            "face turning red",
            "fumbling over words",
            "eyes looking away",
            "awkward silence"
            ],
        "confidence": [
            "believing in oneself",
            "walking tall and proud",
            "unshaken by doubt",
            "ready for anything",
            "owning the moment",
            "feeling powerful and capable",
            "clear and assertive",
            "strong sense of self",
            "radiating assurance",
            "focused and determined"
            ],
    "loneliness": [
            "feeling completely alone",
            "craving connection",
            "an empty room inside",
            "silent and isolated",
            "longing for someone",
            "nobody to talk to",
            "detached from the world",
            "unnoticed and forgotten",
            "aching for companionship",
            "solitude that stings"
            ],
    "insecurity": [
            "questioning self-worth",
            "afraid of being judged",
            "doubting every move",
            "comparing with others",
            "searching for validation",
            "feeling not good enough",
            "worried about appearance",
            "sensitive to criticism",
            "walking on eggshells",
            "trying to fit in"
            ],
    "excitement": [
            "heart racing with joy",
            "buzzing with energy",
            "can’t wait for what’s next",
            "thrilled to the core",
            "jumping with anticipation",
            "eyes sparkling with thrill",
            "restless and eager",
            "filled with joyful energy",
            "voice raised in glee",
            "ready to explode with happiness"
            ],
    "relief": [
            "a weight lifted off",
            "sighing deeply",
            "finally at peace",
            "tension melting away",
            "free from worry",
            "problem solved",
            "let go of fear",
            "a calm after the storm",
            "safe and sound",
            "releasing the breath held"
            ],
    "admiration": [
            "deep respect and awe",
            "looking up to someone",
            "inspired by greatness",
            "praising with sincerity",
            "noticing the best in others",
            "wanting to emulate",
            "honoring achievements",
            "filled with respect",
            "genuine appreciation",
            "seeing true value"
            ],
    "frustration": [
            "blocked at every turn",
            "trying but failing",
            "clenching fists in irritation",
            "wanting to scream",
            "everything going wrong",
            "grinding teeth in anger",
            "fed up and done",
            "pacing with impatience",
            "faced with obstacles",
            "near the breaking point"
            ],
    "tenderness": [
            "soft and gentle feelings",
            "a loving gaze",
            "kindness in every touch",
            "nurturing someone dear",
            "holding with care",
            "heart swelling softly",
            "delicate affection",
            "warm emotional closeness",
            "a soothing embrace",
            "empathy and warmth"
            ],
    "resentment": [
            "harboring old grudges",
            "bitterness in the heart",
            "unspoken anger",
            "replaying the wrongs",
            "unable to forgive",
            "clinging to past hurt",
            "feeling unfairly treated",
            "poisoned by envy",
            "simmering with rage",
            "resentful silence"
            ],
    "serenity": [
            "calm and quiet mind",
            "peace like a still lake",
            "unbothered and balanced",
            "breathing in stillness",
            "content in the present",
            "gentle and tranquil",
            "unmoved by chaos",
            "deep inner peace",
            "completely relaxed",
            "floating in calm"
            ],
    "regret": [
            "wishing things were different",
            "haunted by mistakes",
            "can't take it back",
            "saying 'if only'",
            "feeling remorseful",
            "longing for a redo",
            "troubled by the past",
            "owning up to faults",
            "a heavy conscience",
            "lost opportunities"
            ],
    "awe": [
            "speechless before greatness",
            "moved by the vastness",
            "feeling tiny in the universe",
            "chills from beauty",
            "overcome with wonder",
            "eyes wide with admiration",
            "standing in reverence",
            "inspired to the core",
            "emotion beyond words",
            "a divine presence felt"
            ],
    "compassion": [
            "feeling another’s pain",
            "offering a shoulder to cry on",
            "heart open to others",
            "helping without judgment",
            "soothing someone’s hurt",
            "gentle understanding",
            "walking in their shoes",
            "kindness in action",
            "genuinely caring",
            "emotional generosity"
            ],
    "euphoria": [
            "ecstatic beyond words",
            "floating in bliss",
            "high on happiness",
            "completely overjoyed",
            "pure emotional high",
            "laughing uncontrollably",
            "bursting with delight",
            "on cloud nine",
            "intense wave of joy",
            "feeling unstoppable"
            ],
    "anticipation": [
            "eagerly waiting",
            "counting the seconds",
            "butterflies in the stomach",
            "on the edge of your seat",
            "building excitement",
            "eyes on the prize",
            "restless with hope",
            "bracing for the moment",
            "checking the time constantly",
            "feeling the suspense"
            ],
    "despair": [
            "utter hopelessness",
            "drowning in sorrow",
            "giving up completely",
            "lost in the darkness",
            "no light at the end",
            "crying from the soul",
            "feeling completely broken",
            "nothing left to hold onto",
            "overwhelmed by pain",
            "shattered spirit"
            ],
    "joy": [
            "happiness and celebration",
            "feeling excited and cheerful", 
            "pure joy and elation",
            "dancing with happiness",
            "smiling and laughing",
            "overcome with delight",
            "radiating positivity",
            "a heart full of sunshine",
            "jumping with glee",
            "grinning from ear to ear"
            ],
    "sadness": [
            "feeling melancholy and blue",
            "heartbreak and sorrow",
            "crying and feeling down",
            "loneliness and despair",
            "missing someone deeply",
            "weighed down by emotion",
            "silent tears falling",
            "a heavy heart",
            "wishing things were different",
            "overwhelmed with grief"
            ],
    "anger": [
            "rage and frustration",
            "feeling furious and mad",
            "wanting to fight back",
            "irritation and annoyance",
            "burning with anger",
            "clenched fists and shouting",
            "boiling with fury",
            "gritting teeth in rage",
            "seeing red",
            "tension ready to explode"
            ],
    "love": [
            "deep romantic love",
            "caring for someone special",
            "feeling connected and intimate",
            "devotion and affection",
            "being in love completely",
            "a warm embrace",
            "hearts beating as one",
            "unconditional support",
            "gentle touch and closeness",
            "love that fills the soul"
            ],
    "fear": [
            "anxiety and worry",
            "feeling scared and nervous",
            "panic and dread",
            "being afraid and uncertain",
            "trembling with fear",
            "heart racing with terror",
            "paralyzed by fright",
            "dark thoughts looming",
            "jumping at shadows",
            "unable to feel safe"
            ],
    "hope": [
            "optimism for the future",
            "believing in better days",
            "faith and determination",
            "looking forward with hope",
            "dreams coming true",
            "holding on through trials",
            "light at the end of the tunnel",
            "strength to carry on",
            "a reason to believe",
            "hope shining through darkness"
            ],
    "nostalgia": [
            "remembering the good old days",
            "missing childhood memories",
            "longing for the past",
            "bittersweet reminiscence",
            "wishing to go back in time",
            "smiling through tears",
            "old songs bringing memories",
            "pages of an old photo album",
            "a scent that brings it all back",
            "time slipping through fingers"
            ]
    }
